### ISSUE TITLE
ReferenceError: Can't find variable: paytm

### ISSUE THREAD

**Issue by chakri3130** [ArunYogi/paytm-cordova-plugin#34] opened 2019-11-27 11:01 UTC
Hi @ArunYogi , We are trying use Paytm in my app. We followed each and every step suggested by you. W are happy to say plugin is working in Android app,But while checking with iOS app its returning an error.
Please help me to resolve this issue.
Thanks in advance.

I am working on Ionic3 version.

ReferenceError: Can't find variable: paytm
initiatePaymentRequest — payment.ts:274
(anonymous function) — payment.ts:242
__tryOrUnsub — Subscriber.js:242
next — Subscriber.js:189
_next — Subscriber.js:129
next — Subscriber.js:93
_next — map.js:85
next — Subscriber.js:93
_next — Subscriber.js:129
_next — timeout.js:132
next — Subscriber.js:93
onLoad — http.js:1591
onInvokeTask — core.js:4751
runTask — polyfills.js:3:10845
invokeTask — polyfills.js:3:16802
p — polyfills.js:2:27655
v — polyfills.js:2:27895
defaultErrorLogger — core.js:1449
handleError — core.js:1510
handleError — ionic-error-handler.js:61
next — core.js:5508:118
(anonymous function) — core.js:4342
__tryOrUnsub — Subscriber.js:242
next — Subscriber.js:189
_next — Subscriber.js:129
next — Subscriber.js:93
next — Subject.js:55
emit — core.js:4322
run — polyfills.js:3:10150
onHandleError — core.js:4782
runTask — polyfills.js:3:10900
invokeTask — polyfills.js:3:16802
p — polyfills.js:2:27655
v — polyfills.js:2:27895
defaultErrorLogger — core.js:1449

**Comment by ArunYogi** [comment] 2019-12-11 17:15
check whether the files are properly transfered in plugins/paytm-cordova-plugin folder. If not, just remove the plugin folder & entry in package.json & config.xml and add the plugin again. That will solve the problem

**Comment by ArunYogi** [comment] 2019-12-11 17:19
This issue is a duplicate of #15  #8

**Closed as completed** 2019-12-20 08:46 UTC
